### ISSUE TITLE
_to_str() won't work on a None object

### ISSUE THREAD

**Issue by markprins** [klen/dealer#15]
When a None item is passed to the _to_str() function it fails because None has no attribute decode.

This happens, for instance, when there is no tag set and it tries to return the tag value (which is None instead of an empty string).

Adding a simple check on if it is None and thus returning an empty string would probably solve this.

**Comment by luckydonald** [comment]
Jep, happens here too.

**Comment by luckydonald** [comment]
Why exactly aren't you using ```str(obj)```?
